#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: pyproject
# autospec version: v21
# autospec commit: 8b93847
#
Name     : pypi-ua_parser_builtins
Version  : 1.0.1
Release  : 1
URL      : https://github.com/ua-parser/uap-python/archive/refs/tags/1.0.1.tar.gz
Source0  : https://github.com/ua-parser/uap-python/archive/refs/tags/1.0.1.tar.gz
Source1  : https://github.com/ua-parser/uap-core/archive/refs/tags/v0.6.9.tar.gz
Summary  : Precompiled rules for User Agent Parser
Group    : Development/Tools
License  : Apache-2.0
Requires: pypi-ua_parser_builtins-license = %{version}-%{release}
Requires: pypi-ua_parser_builtins-python = %{version}-%{release}
Requires: pypi-ua_parser_builtins-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(py)
BuildRequires : pypi(pyyaml)
BuildRequires : pypi(setuptools)
BuildRequires : pypi(setuptools_scm)
BuildRequires : pypi-hatchling
BuildRequires : pypi-pluggy
BuildRequires : pypi-pytest
BuildRequires : pypi-tox
BuildRequires : pypi-ua_parser
BuildRequires : pypi-versioningit
BuildRequires : pypi-virtualenv
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Get-version-from-json-file.patch

%description
uap-python
==========
Official python implementation of the `User Agent String
Parser <https://github.com/ua-parser>`_ project.

%package license
Summary: license components for the pypi-ua_parser_builtins package.
Group: Default

%description license
license components for the pypi-ua_parser_builtins package.


%package python
Summary: python components for the pypi-ua_parser_builtins package.
Group: Default
Requires: pypi-ua_parser_builtins-python3 = %{version}-%{release}

%description python
python components for the pypi-ua_parser_builtins package.


%package python3
Summary: python3 components for the pypi-ua_parser_builtins package.
Group: Default
Requires: python3-core
Provides: pypi(ua_parser_builtins)

%description python3
python3 components for the pypi-ua_parser_builtins package.


%prep
%setup -q -n uap-python-1.0.1
cd %{_builddir}
tar xf %{_sourcedir}/v0.6.9.tar.gz
cd %{_builddir}/uap-python-1.0.1
mkdir -p uap-core
cp -r %{_builddir}/uap-core-0.6.9/. %{_builddir}/uap-python-1.0.1/uap-core
%patch -P 1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1739551527
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
pushd ua-parser-builtins
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-ua_parser_builtins
cp %{_builddir}/uap-core-0.6.9/LICENSE %{buildroot}/usr/share/package-licenses/pypi-ua_parser_builtins/bb5c52505e1cdf897b570648717e2098ac74618b || :
cp %{_builddir}/uap-python-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pypi-ua_parser_builtins/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
pushd ua-parser-builtins
python3 -m installer --destdir=%{buildroot} dist/*.whl
popd
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-ua_parser_builtins/2b8b815229aa8a61e483fb4ba0588b8b6c491890
/usr/share/package-licenses/pypi-ua_parser_builtins/bb5c52505e1cdf897b570648717e2098ac74618b

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
